#!/usr/bin/env zsh

### PATH
# mnemonic: [Y]ubikey [auth]
# Use yubikey to authenticate
# press [escape] to go back to directory listing, [escape] twice to exit completely

local oath=$(ykman oath list | eval "fzf ${FZF_DEFAULT_OPTS} --header='[Get oath authentication code]'")

if [[ $oath ]]; then
  local long_code=$(ykman oath code $oath)
  local code=$(echo "$long_code" | awk '{print $2}')
fi
echo "The following code was copied to the clipboard"
echo $code | xsel --clipboard
echo $code
